/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "e2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SimpleMessage, SimpleMessage, AUTO)


PB_BIND(E2_request, E2_request, AUTO)


PB_BIND(E2_dummy_response, E2_dummy_response, AUTO)



